# Generated by Django 5.2.9 on 2026-01-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprogram',
            name='burn_rules',
            field=models.JSONField(blank=True, default=dict, help_text='JSONLogic rules for burning/redeeming points'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='earn_caps_config',
            field=models.JSONField(blank=True, default=list, help_text='Caps on earning points per period (JSON config)'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='earn_rules',
            field=models.JSONField(blank=True, default=dict, help_text='JSONLogic rules for earning points'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='points_expiry_rules',
            field=models.JSONField(blank=True, default=list, help_text='Rules for points expiry'),
        ),
        migrations.AddField(
            model_name='partner',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
