# Generated by Django 5.2.9 on 2026-01-07 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_add_program_rules_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='structure',
            field=models.JSONField(blank=True, default=dict, help_text='Journey structure with nodes and edges (for UI)'),
        ),
        migrations.AddField(
            model_name='journeyexecution',
            name='context',
            field=models.JSONField(blank=True, default=dict, help_text='Execution context with customer data and action results'),
        ),
        migrations.AddField(
            model_name='journeyexecution',
            name='state',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='earncap',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earn_cap_instances', to='loyalty.loyaltyprogram'),
        ),
        migrations.AlterField(
            model_name='journeyexecution',
            name='current_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='loyalty.journeynode'),
        ),
    ]
