# Generated by Django 5.2.9 on 2026-01-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_add_delivery_channel_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLifecycleStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.UUIDField(db_index=True)),
                ('stage', models.CharField(choices=[('acquisition', 'Acquisition'), ('onboarding', 'Onboarding'), ('growth', 'Growth'), ('retention', 'Retention'), ('win_back', 'Win-back'), ('churn_risk', 'Churn Risk'), ('churned', 'Churned')], max_length=50)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('transition_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-entered_at'],
                'indexes': [models.Index(fields=['customer_id', '-entered_at'], name='loyalty_cus_custome_47a61b_idx'), models.Index(fields=['stage', 'entered_at'], name='loyalty_cus_stage_ec6aa9_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerValueSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.UUIDField(db_index=True, unique=True)),
                ('segment', models.CharField(choices=[('high_value', 'High Value'), ('medium_value', 'Medium Value'), ('low_value', 'Low Value')], max_length=50)),
                ('lifetime_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predicted_ltv', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('value_score', models.DecimalField(decimal_places=2, help_text='0-100 score', max_digits=5)),
                ('rfm_segment', models.CharField(blank=True, max_length=50)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-value_score'],
                'indexes': [models.Index(fields=['segment', '-value_score'], name='loyalty_cus_segment_72e982_idx'), models.Index(fields=['customer_id'], name='loyalty_cus_custome_d66a6f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.IntegerField(help_text='Numeric ID used by ML models (0-7 for NBO)', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('points', 'Points'), ('discount', 'Discount'), ('shipping', 'Free Shipping'), ('access', 'VIP Access'), ('special', 'Special Event'), ('referral', 'Referral'), ('sale', 'Sale'), ('tier', 'Tier Upgrade'), ('retention', 'Retention'), ('acquisition', 'Acquisition')], default='points', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('lifecycle_stage', models.CharField(blank=True, choices=[('acquisition', 'Acquisition'), ('onboarding', 'Onboarding'), ('growth', 'Growth'), ('retention', 'Retention'), ('win_back', 'Win-back'), ('churn', 'Churn Risk')], help_text='Target lifecycle stage for this offer', max_length=50, null=True)),
                ('target_value_segment', models.CharField(choices=[('high_value', 'High Value'), ('medium_value', 'Medium Value'), ('low_value', 'Low Value'), ('all', 'All Segments')], default='all', max_length=50)),
                ('min_customer_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_customer_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('external_offer_id', models.CharField(blank=True, help_text='ID in external system (Xiva, CRM, etc.)', max_length=255)),
                ('external_system', models.CharField(choices=[('xiva', 'Xiva'), ('crm', 'CRM'), ('manual', 'Manual')], default='manual', max_length=50)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['offer_id'],
                'indexes': [models.Index(fields=['offer_id', 'is_active'], name='loyalty_off_offer_i_78c717_idx'), models.Index(fields=['lifecycle_stage', 'is_active'], name='loyalty_off_lifecyc_e09910_idx'), models.Index(fields=['target_value_segment', 'is_active'], name='loyalty_off_target__68fd10_idx')],
            },
        ),
    ]
