# Generated by Django 5.2.9 on 2026-01-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0006_customerlifecyclestage_customervaluesegment_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ml', 'ML Configuration'), ('dwh', 'DWH Configuration'), ('feature_store', 'Feature Store'), ('xiva', 'Xiva Integration'), ('general', 'General Settings')], db_index=True, max_length=50)),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('value', models.JSONField(help_text='Configuration value (can be any JSON-serializable type)')),
                ('description', models.TextField(blank=True, help_text='Description of what this configuration does')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('updated_by', models.CharField(blank=True, help_text='User/system that last updated this', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'db_table': 'system_configuration',
                'indexes': [models.Index(fields=['category', 'key'], name='system_conf_categor_79a857_idx'), models.Index(fields=['category', 'is_active'], name='system_conf_categor_c048c6_idx')],
                'unique_together': {('category', 'key')},
            },
        ),
    ]
