# Generated by Django 5.2.9 on 2026-01-22 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0007_systemconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBehaviorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.UUIDField(db_index=True, unique=True)),
                ('engagement_score', models.FloatField(default=0, help_text='How active (0-100)')),
                ('revenue_score', models.FloatField(default=0, help_text='How valuable (0-100)')),
                ('loyalty_score', models.FloatField(default=0, help_text='How long & stable (0-100)')),
                ('risk_score', models.FloatField(default=0, help_text='Churn probability (0-100)')),
                ('digital_score', models.FloatField(default=0, help_text='App/digital usage (0-100)')),
                ('score_breakdown', models.JSONField(blank=True, default=dict, help_text='Detailed breakdown of how scores were calculated')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculation_version', models.CharField(default='1.0', help_text='Scoring algorithm version', max_length=50)),
            ],
            options={
                'db_table': 'customer_behavior_score',
            },
        ),
        migrations.CreateModel(
            name='CustomerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(choices=[('CALL_OUTGOING', 'Outgoing Call'), ('CALL_INCOMING', 'Incoming Call'), ('DATA_USAGE', 'Data Usage'), ('SMS_SENT', 'SMS Sent'), ('SMS_RECEIVED', 'SMS Received'), ('RECHARGE', 'Recharge'), ('TOP_UP', 'Top-up'), ('BUNDLE_PURCHASE', 'Bundle Purchase'), ('PAYMENT', 'Payment'), ('BILL_PAID', 'Bill Paid'), ('APP_LOGIN', 'App Login'), ('APP_FEATURE_USE', 'App Feature Used'), ('USSD_MENU', 'USSD Menu Access'), ('WEB_LOGIN', 'Web Login'), ('CONTENT_VIEW', 'Content Viewed'), ('ACTIVATION', 'Account Activation'), ('STATUS_CHANGE', 'Status Change'), ('PROFILE_UPDATE', 'Profile Update'), ('QOE_ISSUE', 'Quality of Experience Issue'), ('NETWORK_EVENT', 'Network Event'), ('CUSTOM', 'Custom Event')], db_index=True, max_length=50)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric value (MB, $, count, etc.)', max_digits=15, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('source', models.CharField(db_index=True, help_text='Source system: cdr, billing, app, crm, network', max_length=50)),
                ('source_event_id', models.CharField(blank=True, help_text='Original event ID from source system', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context: duration, destination, product, etc.')),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer_event',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DataSourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('cdr', 'CDR (Call Detail Records)'), ('billing', 'Billing/OCS'), ('crm', 'CRM/Subscriber DB'), ('app', 'App/Web/USSD'), ('network', 'Network/QoE'), ('dwh', 'Data Warehouse'), ('xiva', 'Xiva System')], db_index=True, max_length=50)),
                ('source_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('connection_config', models.JSONField(default=dict, help_text='Connection details: API endpoint, DB connection, credentials, etc.')),
                ('event_mapping', models.JSONField(default=dict, help_text='Maps source event fields to normalized event structure')),
                ('sync_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Source Configuration',
                'verbose_name_plural': 'Data Source Configurations',
                'db_table': 'data_source_config',
            },
        ),
        migrations.CreateModel(
            name='MissionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('onboarding', 'Onboarding (Lifecycle)'), ('engagement', 'Engagement'), ('revenue', 'Revenue (ARPU)'), ('loyalty', 'Loyalty'), ('correction', 'Behavioral Correction')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('metric', models.CharField(choices=[('data_usage', 'Data Usage'), ('call_count', 'Call Count'), ('sms_count', 'SMS Count'), ('total_usage', 'Total Usage'), ('recharge_amount', 'Recharge Amount'), ('bundle_purchase', 'Bundle Purchase'), ('arpu', 'ARPU'), ('spend', 'Total Spend'), ('app_login', 'App Login'), ('feature_use', 'Feature Usage'), ('content_view', 'Content View'), ('streak_days', 'Streak Days'), ('active_days', 'Active Days'), ('on_time_payment', 'On-Time Payment'), ('no_inactivity', 'No Inactivity Period'), ('custom', 'Custom Metric')], max_length=50)),
                ('threshold', models.JSONField(default=dict, help_text="Threshold configuration: {'value': 100, 'operator': '>='} or parameterized")),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom Period')], default='weekly', max_length=20)),
                ('reward_config', models.JSONField(default=dict, help_text="Reward configuration: {'points': 100, 'badge_id': 1, 'offer_id': 2}")),
                ('eligibility_rules', models.JSONField(blank=True, default=dict, help_text='JSONLogic rules for who can get this mission')),
                ('generation_rules', models.JSONField(blank=True, default=dict, help_text="Rules for when to generate: {'min_engagement_score': 30, 'max_risk_score': 70}")),
                ('badge_type', models.CharField(blank=True, help_text='Badge type to award', max_length=50)),
                ('badge_level', models.CharField(blank=True, help_text='Badge level: bronze, silver, gold, platinum', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Priority for generation (higher = more important)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mission_template',
            },
        ),
        migrations.AddField(
            model_name='badge',
            name='auto_award_rules',
            field=models.JSONField(blank=True, default=dict, help_text='JSONLogic rules for auto-awarding this badge'),
        ),
        migrations.AddField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('activated', 'Activated'), ('30_days_active', '30 Days Active'), ('90_days_loyal', '90 Days Loyal'), ('power_user', 'Power User'), ('app_champion', 'App Champion'), ('big_spender', 'Big Spender'), ('premium', 'Premium'), ('self_care_pro', 'Self-Care Pro'), ('auto_renew', 'Auto-Renew'), ('referrer', 'Referrer'), ('comeback_hero', 'Comeback Hero'), ('custom', 'Custom')], db_index=True, default='achievement', max_length=50),
        ),
        migrations.AddField(
            model_name='badge',
            name='level',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], db_index=True, default='bronze', max_length=20),
        ),
        migrations.AddField(
            model_name='badge',
            name='unlock_order',
            field=models.IntegerField(default=0, help_text='Order in which badge levels unlock'),
        ),
        migrations.AddField(
            model_name='mission',
            name='category',
            field=models.CharField(blank=True, choices=[('onboarding', 'Onboarding'), ('engagement', 'Engagement'), ('revenue', 'Revenue'), ('loyalty', 'Loyalty'), ('correction', 'Behavioral Correction')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='generated_for',
            field=models.UUIDField(blank=True, help_text='Customer ID if personalized mission', null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='is_dynamic',
            field=models.BooleanField(default=False, help_text='True if generated dynamically from template'),
        ),
        migrations.AddField(
            model_name='mission',
            name='metric',
            field=models.CharField(blank=True, help_text='Metric to track: data_usage, recharge_amount, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='mission',
            name='reward_config',
            field=models.JSONField(blank=True, default=dict, help_text='Reward configuration: points, badges, offers'),
        ),
        migrations.AddField(
            model_name='mission',
            name='target_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='loyalty.segment'),
        ),
        migrations.AddField(
            model_name='mission',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target value for mission', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='requirements',
            field=models.JSONField(default=dict, help_text="Badge requirements: {'min_engagement_score': 70, 'mission_completed': 'mission_id'}"),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_type',
            field=models.CharField(choices=[('points_earn', 'Earn Points'), ('points_burn', 'Burn Points'), ('transaction_count', 'Transaction Count'), ('streak', 'Streak'), ('data_usage', 'Data Usage'), ('recharge', 'Recharge'), ('engagement', 'Engagement'), ('revenue', 'Revenue'), ('loyalty', 'Loyalty'), ('correction', 'Behavioral Correction'), ('custom', 'Custom')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['badge_type', 'level'], name='loyalty_bad_badge_t_c7e170_idx'),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['unlock_order'], name='loyalty_bad_unlock__855c34_idx'),
        ),
        migrations.AddIndex(
            model_name='customerbehaviorscore',
            index=models.Index(fields=['engagement_score'], name='customer_be_engagem_2abfca_idx'),
        ),
        migrations.AddIndex(
            model_name='customerbehaviorscore',
            index=models.Index(fields=['revenue_score'], name='customer_be_revenue_b13c32_idx'),
        ),
        migrations.AddIndex(
            model_name='customerbehaviorscore',
            index=models.Index(fields=['risk_score'], name='customer_be_risk_sc_7fa1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='customerbehaviorscore',
            index=models.Index(fields=['-updated_at'], name='customer_be_updated_ee8c01_idx'),
        ),
        migrations.AddIndex(
            model_name='customerevent',
            index=models.Index(fields=['customer_id', 'timestamp'], name='customer_ev_custome_fa7c11_idx'),
        ),
        migrations.AddIndex(
            model_name='customerevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='customer_ev_event_t_c8288f_idx'),
        ),
        migrations.AddIndex(
            model_name='customerevent',
            index=models.Index(fields=['source', 'timestamp'], name='customer_ev_source_028dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='customerevent',
            index=models.Index(fields=['processed', 'timestamp'], name='customer_ev_process_2d6344_idx'),
        ),
        migrations.AddIndex(
            model_name='missiontemplate',
            index=models.Index(fields=['category', 'is_active'], name='mission_tem_categor_f87d25_idx'),
        ),
        migrations.AddIndex(
            model_name='missiontemplate',
            index=models.Index(fields=['metric', 'is_active'], name='mission_tem_metric_5d60bd_idx'),
        ),
        migrations.AddField(
            model_name='mission',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='loyalty.missiontemplate'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['category', 'is_active'], name='loyalty_mis_categor_b4ff9e_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['is_dynamic', 'generated_for'], name='loyalty_mis_is_dyna_6d5bae_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['template', 'is_active'], name='loyalty_mis_templat_87daa6_idx'),
        ),
    ]
