# Generated by Django 5.2.9 on 2026-01-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0008_customerbehaviorscore_customerevent_datasourceconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_product_id', models.CharField(help_text='Product ID in external system', max_length=255)),
                ('external_system', models.CharField(choices=[('xiva', 'Xiva'), ('crm', 'CRM'), ('billing', 'Billing/OCS'), ('manual', 'Manual')], default='manual', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('voice', 'Voice Plan'), ('data', 'Data Plan'), ('sms', 'SMS Plan'), ('bundle', 'Bundle Plan'), ('device', 'Device'), ('service', 'Service'), ('addon', 'Add-on')], default='bundle', max_length=50)),
                ('category', models.CharField(blank=True, help_text="Product category (e.g., 'Postpaid', 'Prepaid')", max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('recurring', models.BooleanField(default=False, help_text='Is this a recurring subscription?')),
                ('billing_cycle', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('one_time', 'One-time')], default='monthly', max_length=20)),
                ('features', models.JSONField(blank=True, default=dict, help_text='Product features (data allowance, minutes, etc.)')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Additional attributes (brand, model, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True, help_text='Available for purchase')),
                ('target_segments', models.JSONField(blank=True, default=list, help_text='Target customer segments')),
                ('min_customer_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_customer_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('sync_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('manual', 'Manual')], default='daily', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='loyaltyevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='loyaltytier',
            options={'ordering': ['priority', 'min_points']},
        ),
        migrations.AlterModelOptions(
            name='loyaltytransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='loyaltyaccount',
            unique_together={('customer_id', 'program')},
        ),
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='burn_rules',
        ),
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='earn_caps_config',
        ),
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='earn_rules',
        ),
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='points_expiry_rules',
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='lifetime_points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='lifetime_points_redeemed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loyaltyaccount',
            name='customer_id',
            field=models.UUIDField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='loyaltyaccount',
            name='points_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['object_type', 'object_id'], name='loyalty_aud_object__691e66_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor_id', '-timestamp'], name='loyalty_aud_actor_i_85d8da_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyaccount',
            index=models.Index(fields=['customer_id'], name='loyalty_loy_custome_4d2491_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyaccount',
            index=models.Index(fields=['program', 'tier'], name='loyalty_loy_program_d8e96d_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyevent',
            index=models.Index(fields=['account', '-created_at'], name='loyalty_loy_account_d52159_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyevent',
            index=models.Index(fields=['event_type', '-created_at'], name='loyalty_loy_event_t_f8e515_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['account', '-created_at'], name='loyalty_loy_account_383e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['external_product_id', 'external_system'], name='loyalty_pro_externa_9d7c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'is_active'], name='loyalty_pro_product_48e1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_available'], name='loyalty_pro_is_acti_313284_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('external_product_id', 'external_system')},
        ),
        migrations.RemoveField(
            model_name='loyaltyaccount',
            name='status',
        ),
    ]
