# Generated by Django 5.2.9 on 2026-01-22 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0009_product_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='offer_config',
            field=models.JSONField(blank=True, default=dict, help_text='Offer configuration (if not using offer_id)'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='offer_id',
            field=models.ForeignKey(blank=True, help_text='Linked offer from offer catalog', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='loyalty.offer'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='product_config',
            field=models.JSONField(blank=True, default=dict, help_text='Product configuration (if not using product_id)'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='product_id',
            field=models.ForeignKey(blank=True, help_text='Linked product from product catalog', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='loyalty.product'),
        ),
    ]
