# Generated by Django 5.2.9 on 2026-01-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0010_campaign_offer_config_campaign_offer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BadgeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BehaviorScoreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='approvaldecision',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='approvalworkflow',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='badgeaward',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='campaignexecution',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='capusage',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='coalition',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customerbehaviorscore',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customerevent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='datasourceconfig',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='deliverychannelconfig',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='earncap',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='experiment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='experimentassignment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='holdoutgroup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='journey',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='journeyedge',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='journeyexecution',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='journeynode',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='leaderboardentry',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='missionprogress',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='missiontemplate',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='partnerprogram',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='partnersettlement',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pointsexpiryevent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pointsexpiryrule',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='segment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='segmentmember',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='segmentsnapshot',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='streak',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='systemconfiguration',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='ExternalSystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="System name (e.g., 'Xiva Production', 'CRM Staging')", max_length=255, unique=True)),
                ('system_type', models.CharField(choices=[('xiva', 'Xiva'), ('crm', 'CRM'), ('billing', 'Billing/OCS'), ('dwh', 'Data Warehouse'), ('other', 'Other')], help_text='Type of external system', max_length=50)),
                ('base_url', models.URLField(help_text='Base URL for API (e.g., https://api.xiva.sa/api)')),
                ('api_version', models.CharField(blank=True, help_text='API version (e.g., v5)', max_length=50)),
                ('auth_type', models.CharField(choices=[('jwt', 'JWT (JSON Web Token)'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth'), ('api_key', 'API Key'), ('oauth2', 'OAuth 2.0'), ('none', 'No Authentication')], default='jwt', max_length=50)),
                ('auth_endpoint', models.CharField(blank=True, help_text='Authentication endpoint (e.g., /auth/token/)', max_length=255)),
                ('refresh_endpoint', models.CharField(blank=True, help_text='Token refresh endpoint (e.g., /auth/token/refresh/)', max_length=255)),
                ('client_id', models.CharField(blank=True, help_text='Client ID or username', max_length=255)),
                ('client_secret', models.CharField(blank=True, help_text='Client secret or password (encrypted)', max_length=255)),
                ('api_key', models.CharField(blank=True, help_text='API key (if auth_type is api_key)', max_length=255)),
                ('api_key_header', models.CharField(default='X-API-Key', help_text='Header name for API key', max_length=100)),
                ('custom_headers', models.JSONField(blank=True, default=dict, help_text="Custom headers to include in requests: {'X-Custom-Header': 'value'}")),
                ('endpoints', models.JSONField(blank=True, default=dict, help_text="API endpoints: {'products': '/productCatalogManagement/v5/productOffering/', 'categories': '/category/'}")),
                ('timeout', models.IntegerField(default=30, help_text='Request timeout in seconds')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum retry attempts')),
                ('retry_backoff', models.CharField(choices=[('exponential', 'Exponential'), ('linear', 'Linear'), ('fixed', 'Fixed')], default='exponential', max_length=50)),
                ('rate_limit_per_minute', models.IntegerField(default=300, help_text='Rate limit per minute')),
                ('rate_limit_per_hour', models.IntegerField(default=10000, help_text='Rate limit per hour')),
                ('max_connections', models.IntegerField(default=20, help_text='Maximum connections in pool')),
                ('max_connections_per_host', models.IntegerField(default=10, help_text='Maximum connections per host')),
                ('token_refresh_buffer', models.IntegerField(default=300, help_text='Refresh token N seconds before expiry')),
                ('token_cache_enabled', models.BooleanField(default=True, help_text='Cache tokens in memory')),
                ('verify_ssl', models.BooleanField(default=True, help_text='Verify SSL certificates')),
                ('ssl_cert_path', models.CharField(blank=True, help_text='Path to SSL certificate (if needed)', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this configuration')),
                ('is_production', models.BooleanField(default=False, help_text='Production environment flag')),
                ('description', models.TextField(blank=True, help_text='Description of this configuration')),
                ('last_tested_at', models.DateTimeField(blank=True, help_text='Last successful API test', null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last successful sync', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['system_type', 'name'],
                'indexes': [models.Index(fields=['system_type', 'is_active'], name='loyalty_ext_system__d9cf7a_idx'), models.Index(fields=['is_active', 'is_production'], name='loyalty_ext_is_acti_0d01a8_idx')],
            },
        ),
    ]
