# Generated by Django 5.2.9 on 2026-01-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0011_badgelevel_badgetype_behaviorscoretype_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerbehaviorscore',
            table=None,
        ),
        migrations.AlterModelTable(
            name='customerevent',
            table=None,
        ),
        migrations.AlterModelTable(
            name='datasourceconfig',
            table=None,
        ),
        migrations.AlterModelTable(
            name='missiontemplate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='systemconfiguration',
            table=None,
        ),
    ]
